### PR TITLE
added user/pass

### PR DESCRIPTION
**Pull request by dirkk0**
since it's not that obvious

### CODE REVIEW

**Comment by simonwep** [comment]
Well, since you're allowed to register a new 
account (and there is no such a admin account with more rights etc. This isn't really necessary, a info "Simply create an Account" would be more helpful ;)

There a things which can "disappear" so it's better that everyone can create an account to the the same experience as everyone else :D

**Comment by simonwep** [comment]
And yeah it seems like someone created an account to with admin as username, hm. That doesn't matter ^^

**Comment by dirkk0** [comment]
Problem is that not many people will rather refrain from registereing; at
least for me it would be the one extra step where I wouldn't bother
checking out the application anymore.

Additionally I would recommend to re-initialize the demo instance on a
regular basis for several reasons like unsoliticed content.

Best, Dirk

**Comment by dirkk0** [comment]
ok, then rather initialize with one user demo/demo or something.

**Comment by simonwep** [comment]
Yeah, I'll add something which clears the database (and everything else) every day! :D good point!

And yes I'll add something regarding registration / login in the readme later :)

**Pull request closed without merging**
